#! /bin/bash

. /home/william/.config/bspwm/bspwm_config.sh

bspc config border_width        3
bspc config window_gap         12
bspc config top_padding        $BAR_HEIGHT


bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config auto_cancel         true

bspc config focused_border_color    "#fdf4c1"
bspc config active_border_color     "#282828"
bspc config normal_border_color     "#282828"
bspc config presel_border_color     "#b8bb26"


bspc monitor DVI-I-1 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 10

# Reload automatically
if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPEM_HISTORY" "$BSPWM_STACK"
fi

# Start it
. /home/william/.autostart.sh &

